# Pull in the layer of the base image: golang:1.11-alpine 
FROM    

# Set author label: LABEL author=[YOUR-EMAIL]
LABEL 

# Set working directory: `/opt`
WORKDIR 

# Copy local file `main.go` to the working directory
COPY 

# List items in the working directory (ls -lsa) and show content of the `main.go`file (cat)
RUN 

# Build the app (CGO_ENABLED=0 go build -o /usr/myapp) and show the /usr directory  (ls -lsa)
RUN 
